* GENRIC-CL

GENERIC-CL provides a generic function wrapper over various functions
in the Common Lisp standard, such as equality predicates and sequence
operations. The goal of the wrapper is to provide a standard interface
to common operations, such as testing for the equality of two objects,
which is extensible to user-defined types.

** Usage

The generic function interface is contained in the ~GENERIC-CL~
package. This package should be used rather than ~COMMON-LISP~, as it
shadows the symbols, in the ~COMMON-LISP~ package, which name a
function for which there is a generic function wrapper. The
~GENERIC-CL~ additionally reexports the remaining non-shadowed symbols
in ~COMMON-LISP~.

** Generic Interfaces

The generic function interface consists of the following functions
divided into the following categories:

*** Equality

The equality interface provides functions for testing objects for
equality.

**** EQUALP

Generic Function: ~EQUALP A B~

Returns true if object ~A~ is equal to object ~B~.

Has methods specialized on the following types:

   - ~NUMBER NUMBER~

     Returns true if ~A~ and ~B~ represent the same numeric value,
     as per ~CL:=~.

   - ~CHARACTER CHARACTER~

     Returns true if ~A~ and ~B~ represent the same character, as per
     ~CL:CHAR=~.

   - ~CONS CONS~

     Returns true if the ~CAR~ of ~A~ is equal (by ~EQUALP~) to the
     ~CAR~ of ~B~ and if the ~CDR~ of ~A~ is equal (by ~EQUALP~) to
     the ~CDR~ of ~B~.

   - ~VECTOR VECTOR~

     Returns true if ~A~ and ~B~ are vectors of the same length and
     each element of ~A~ is equal (by ~EQUALP~) to the corresponding
     element of ~B~.

   - ~ARRAY ARRAY~

     Multi-dimensional arrays.

     Returns true if ~A~ and ~B~ have the same dimensions and each
     element of ~A~ is equal (by ~EQUALP~) to the corresponding
     element of ~B~.

   - ~STRING STRING~

     Returns true if both strings are equal (by ~CL:STRING=~).

   - ~PATHNAME PATHNAME~

     Returns true if both ~PATHNAME~ objects are functionally
     equivalent, as per the ~PATHNAME-EQUAL~ function from the
     ~CL-FAD~ library.

   - ~T T~

     Default method.

     Returns true if ~A~ and ~B~ are the same object,
     as per ~CL:EQ~.


**** =

Function: ~= X &REST XS~

Returns true if all objects in ~XS~ are equal (by ~EQUALP~) to ~X~.

**** /=

Function: ~= X &REST XS~

Returns true if at least one object in ~XS~ is not equal (by ~EQUALP~)
to ~X~.

*** Comparison
*** Arithmetic
*** Objects
*** Iterator
*** Collector
*** Sequence Operations
*** Generic Hash-Tables
*** Set Operations
