=== Generic Hash-Tables ===

System and package name: `GENERIC-CL.MAP`

This interface provides a hash-table data structure with the generic
function <<HASH>> as the hash function and the generic function
<<equalp,GENERIC-CL:EQUALP>> as the key comparison function. This
allows the hash-tables to utilize keys of user-defined types, whereas
the keys of standard hash tables are limited to numbers, characters,
lists and strings.

The generic hash-tables are implemented using
https://github.com/metawilm/cl-custom-hash-table[CL-CUSTOM-HASH-TABLE]. If
the Common Lisp implementation supports creating hash-tables with
user-defined hash and comparison functions, standard hash-tables are
used. However if the implementation does not support user-defined hash
and comparison functions, a fallback solution is used, which is a
custom hash-table implementation on top of standard hash-tables. The
<<HASH-MAP>> structure wraps the custom hash-table which allows
methods methods to be specialized on a single type `HASH-MAP`
regardless of whether standard or custom hash-tables are used.

The functions in this interface are specialized on the `HASH-MAP`
type, thus this type, created with <<MAKE-HASH-MAP>>, should be used
rather than built-in hash-tables. If a hash-table is obtained from an
external source, use <<HASH-MAP>> or <<ENSURE-HASH-MAP>> to convert it
to a `HASH-MAP`.

.*Standard Hash-Table Counterparts*

[width="80%",options="header"]
|====
| `CL:HASH-TABLE`| `HASH-MAP`

| GETHASH| GET
| HASH-TABLE-COUNT| LENGTH
| REMHASH| ERASE
| CLRHASH| CLEAR
|====


==== HASH-MAP ====

Structure: `HASH-MAP`

.Slots
* `TABLE`

Function: `HASH-MAP TABLE`

The `HASH-MAP` structure wraps a standard `HASH-TABLE`, or
`CUSTOM-HASH-TABLE`, contained in the `TABLE` slot, which can be
accessed accessed with `HASH-MAP-TABLE`.

The `HASH-MAP` function takes a single argument, a hash-table, and
creates a `HASH-MAP` wrapping it.


===== Implemented Interfaces =====

The <<CLEARED>>, <<MAKE-SEQUENCE-OF-TYPE>>, <<LENGTH>>, <<EMPTYP>>,
<<CLEAR>>, <<ELT>>, <<setf-elt>> and <<ERASE>> methods of the
<<container>> interface are implemented.

The <<iterator>> interface is implemented for ``HASH-MAP``'s. Each element
returned by the iterator is a `CONS` with the key in the `CAR` and the
corresponding value in the `CDR`. The order in which the entries are
iterated over is unspecified. Likewise it is unspecified which entries
will be iterated over if `START` is non-zero and/or `END` is non-NIL,
the only guarantee being that `END - START` entries are iterated
over. The reverse iterator iterates over the entries in the same order
as the normal iterator due to the order of iteration being
unspecified.

The <<setf-at>> method for the `HASH-MAP` iterator sets the value
corresponding to the key of the current entry, being iterated over, to
the value passed as the argument to `SETF`.

The collector interface is implemented for ``HASH-MAP``'s. The
<<ACCUMULATE>> method expects a `CONS` where the `CAR` is the key of
the entry to create and the `CDR` is the corresponding value.

An <<EQUALP>> method is implemented for ``HASH-MAP``'s which returns
true if both maps contain the same number of entries and each key in
the first map is present in the second map, with the corresponding
value in the first map equal (by `EQUALP`) to the corresponding value
in the second
map.

WARNING: if the two maps have different test functions, the `EQUALP`
method is not necessarily symmetric i.e. `(EQUALP A B)` does not imply
`(EQUALP B A)`.

A <<LIKEP>> method is implemented for ``HASH-MAP``'s, which is similar
to the `EQUALP` method, however the values are compared using `LIKEP`.

A <<COPY>> method is implemented for ``HASH-MAP``'s which by default
creates a new map with the same entries as the original map. If `:DEEP
T` is provided the values (but not the keys as they should be
immutable) are copied by `(COPY VALUE :DEEP T)`.


==== MAKE-HASH-MAP ====

Function: `MAKE-HASH-MAP &KEY TEST &ALLOW-OTHER-KEYS`

Creates a `HASH-MAP` wrapping a hash table with test function `TEST`,
which defaults to `#'GENERIC-CL:EQUALP`.

`TEST` may be one of the following:

`GENERIC-CL:EQUALP`:: A hash table with hash function <<HASH>> and
comparison function <<equalp,GENERIC-CL:EQUALP>> is created.

`LIKEP`:: A hash table with hash function <<LIKE-HASH>> and comparison
function <<LIKEP>> is created.

`TEST` may also be a standard hash-table test specifier, in which case
a native hash table is created, wrapped in a `HASH-MAP`.

The function accepts all additional arguments (including
implementation specific arguments) accepted by `CL:MAKE-HASH-TABLE`.


==== ENSURE-HASH-MAP ====

Function: `ENSURE-HASH-MAP THING`

If `MAP` is a <<HASH-MAP>> returns it, otherwise if `MAP` is a
`HASH-TABLE` or `CUSTOM-HASH-TABLE` returns a `HASH-MAP` which wraps
it. Signals an error if `MAP` is not of the aforementioned types.


==== HASH-MAP-TEST ====

Function: `HASH-MAP-TEST MAP`

Returns the test function, as a symbol, of the underlying hash table.

CAUTION: On some implementations the return value is not
`GENERIC-CL:EQUALP`, even if the hash table has `HASH` and
`GENERIC-CL:EQUALP` as its hash and comparison functions.


==== HASH ====

Generic Function: `HASH OBJECT`

Hash function for hash tables with the `GENERIC-CL:EQUALP` test
specifier.

Return a hash code for `OBJECT`, which should be a non-negative
fixnum. If two objects are equal (under <<equalp, GENERIC-CL:EQUALP>>)
then the hash codes, for the two objects, returned by `HASH`, should
also be equal.

The default method calls `CL:SXHASH` which satisfies the constraint
that `(CL:EQUAL X Y)` implies `(= (CL:SXHASH X) (CL:SXHASH
Y))`.

IMPORTANT: Currently no specialized method is provided for
container/sequence objects such as lists. The default method does not
violate the constraint for lists (but does violate the constraints for
non-string vectors) as keys, provided they only contain numbers,
characters, symbols, strings and other lists as elements.

==== LIKE-HASH ====

Generic Function: `LIKE-HASH OBJECT`

Hash function for hash tables with the `LIKEP` test
specifier.

Return a hash code for `OBJECT`, which should be a non-negative
fixnum. If two objects are equal (under <<LIKEP>>) then the hash
codes, for the two objects, returned by `LIKE-HASH`, should also be
equal.

Methods which satisfy these constraints are provided for strings,
characters, lists, vectors and multi-dimensional arrays. The default
method calls the `HASH` function.


==== GET ====

Generic Function: `GET KEY MAP &OPTIONAL DEFAULT`

Return the value of the entry corresponding to the key `KEY` in the
map `MAP`. If the `MAP` does not contain any entry with that key,
`DEFAULT` is returned. The second return value is true if an entry
with key `KEY` was found in the map, false otherwise.

Methods are provided for ``HASH-MAP``'s, standard ``HASH-TABLE``'s,
association lists (`ALISTS`) and property lists (`PLISTS`). For
`ALISTS` the <<EQUALP>> key comparison function is used. For `PLISTS`
the `EQ` key comparison function is used.


==== (SETF GET) ====

Generic Function: `(SETF GET) VALUE KEY MAP &OPTIONAL DEFAULT`

Set the value of the entry corresponding to the key `KEY` in the map
`MAP`. `DEFAULT` is ignored.

IMPORTANT: Only a method for `HASH-MAPS` and `HASH-TABLES` is
provided.


==== ENSURE-GET ====

Macro: `ENSURE-GET KEY MAP &OPTIONAL DEFAULT`

Like `GET` however if `KEY` is not found in `MAP` it is added, by
`(SETF GET)` with the value `DEFAULT`.

The first return value is the value corresponding to the key `KEY`, or
`DEFAULT` if `KEY` is not found in `MAP`. The second return value is
true if `KEY` was found in `MAP`, false otherwise.


==== ELT Methods ====

The following `ELT` methods are provided:

* `(MAP HASH-MAP) (KEY T)`
+
Returns `(GENERIC-CL:GET KEY MAP)`.

* `(MAP HASH-TABLE) (KEY T)`
+
Returns `(GETHASH KEY MAP)`


==== (SETF ELT) Methods ====

The following `(SETF ELT)` methods are provided:

* `(VALUE T) (MAP HASH-MAP) (KEY T)`
+
Calls `(SETF (GENERIC-CL:GET KEY MAP) VALUE)`

* `(VALUE T) (MAP HASH-TABLE) (KEY T)`
+
Calls `(SETF (GETHASH KEY MAP) VALUE)`


==== ERASE Method ====

Method: `ERASE (MAP HASH-MAP) (KEY T)`

Remove the entry with key `KEY` from `MAP`.

Returns true if the map contained an entry with key `KEY`.


==== HASH-MAP-ALIST ====

Function: `HASH-MAP-ALIST MAP`

Returns an association list (`ALIST`) containing all the entries in
the map `MAP`.


==== ALIST-HASH-MAP ====

Function: `ALIST-HASH-MAP ALIST &REST ARGS`

Returns a <<HASH-MAP>> containing all entries in the association list
`ALIST`.

`ARGS` are the additional arguments passed to <<MAKE-HASH-MAP>>.


==== MAP-KEYS ====

Generic Function: `MAP-KEYS MAP`

Return a sequence containing all the keys in the map `MAP`.

NOTE: Specialized only on ``HASH-MAP``'s and ``CL:HASH-TABLE``'s.


==== MAP-VALUES ====

Generic Function: `MAP-VALUES MAP`

Return a sequence containing all the values in the map `MAP`.

NOTE: Specialized only on ``HASH-MAP``'s and ``CL:HASH-TABLE``'s.


==== COERCE Methods ====

The following `COERCE` methods are provided for `HASH-MAPS`:

* `HASH-MAP (EQL 'ALIST)`
+
Returns an association list (`ALIST`) containing all the entries in
the map. Equivalent to <<HASH-MAP-ALIST>>.

* `HASH-MAP (EQL 'PLIST)`
+
Returns a property list (`PLIST`) containing all the entries in
the map.

==== MAKE-SEQUENCE-OF-TYPE Method ====

Method: `MAKE-SEQUENCE-OF-TYPE (TYPE (EQL 'HASH-MAP)) (ARGS NULL)`

Return a new empty `HASH-MAP` with test function `GENERIC-CL:EQUALP`.
